route:
  receiver: 'slack-notifications'
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 3h

receivers:
- name: 'slack-notifications'
  slack_configs:
  - send_resolved: True
    api_url: 'https://hooks.slack.com/services/{webhook}'
    text: 'Alert: {{ .CommonAnnotations.summary }}. Description: {{ .CommonAnnotations.description }}'
