version: '3.7'
services:
  api:
    build: ./api
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.30.0
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager:v0.23.0
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - --config.file=/etc/alertmanager/config.yml
    ports:
      - 9093:9093
