global:
  scrape_interval: 5s

rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
